### ISSUE TITLE
Empty Profile list

### ISSUE THREAD

**Issue by KabelManRoel** [apollo-ng/picoReflow#13]
Problem: Empty Profile list by starting
               after edit new profile the list is filed
               when using Internet Explorer 11
Solution: use Chrome all problems wiht showing profiles list are solved

**Comment by chron0** [comment]
Ah, yes, we never test IE, since we don't have windows and don't use/support proprietary, patent-encumbered systems at all. If someone is willing to waste their lifetime to test/fix this, please submit a PR. Otherwise please use FF and Chromium or any other, newer WebKit based browser.
