### ISSUE TITLE
error raised by MAX31855.py after a few seconds of temperature increase

### ISSUE THREAD

**Issue by davelloper** [apollo-ng/picoReflow#22]
The oven crashes after a few seconds of temperature increase (securely, it stops the heat) since in function checkErrors there is a binary comparison between a 32 bit value and what could be interpreted by python as either 8,16 or 32 bit value. Namely:

`anyErrors = (data_32 & 0x10000) != 0    # Fault bit, D16
        noConnection = (data_32 & 1) != 0       # OC bit, D0
        shortToGround = (data_32 & 2) != 0      # SCG bit, D1
shortToVCC = (data_32 & 4) != 0 # SCV bit, D2`

changing the above code to 

`     anyErrors = (data_32 & 0x10000) != 0    # Fault bit, D16
        noConnection = (data_32 & 0x00000001) != 0       # OC bit, D0
        shortToGround = (data_32 & 0x00000002) != 0      # SCG bit, D1
        shortToVCC = (data_32 & 0x00000004) != 0         # SCV bit, D2`

fixes the issue. 
should I make a pull request?

**Comment by chron0** [comment]
That would be lovely :)

**Comment by chron0** [comment]
Closed with #23
