### ISSUE TITLE
Fresh Install Failed - failed with error code 1 in None

### ISSUE THREAD

**Issue by diginfo** [apollo-ng/picoReflow#32]
Just did a fresh install of raspian, installed the dependancies and it failed with:

`(Command "/usr/bin/python -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-Gl8GoM --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- "setuptools >= 40.8.0" wheel "Cython >= 3.0a6" "cffi >= 1.12.3 ; platform_python_implementation == 'CPython'" "greenlet >= 0.4.17, < 2.0 ; platform_python_implementation == 'CPython'"" failed with error code 1 in None)`

Any ideas ??

**Comment by chron0** [comment]
Without testing my first guess would be Python 3.x - Back when it was released it was python 2.x and I havent tracked the PRs if 3.x compatibility was merged. If you still have python2/pip2 available you could try it with that. I may have some more reflow coming up in the future where I want to migrate the whole thing to an ESP32 - that would be smaller, cheaper and rid us of the linux/python dependencies.

**Comment by diginfo** [comment]
Thanks, Solved:

`apt install libffi-dev`

**Comment by chron0** [comment]
<3 - great - and thanks for the solution feedback that may help others.

**Comment by diginfo** [comment]
Thanks, now I am unable to save a new profile:

`An oven is not a time-machine`
<img width="1176" alt="Screenshot 2021-07-17 at 8 26 53 PM" src="https://user-images.githubusercontent.com/6010010/126036826-a5b68487-8490-47db-b517-1041877d686b.png">

**Comment by chron0** [comment]
as it says: an oven is not a time machine :) your first target time is 900 seconds, your seconds point is 45 seconds into runtime - that would have to let move back in time to get there. A Point in Target time cannot be lower than the prior one.

**Comment by chron0** [comment]
See my example:

![Image](https://apollo.open-resource.org/_media/mission:resources:picoreflow_webinterface_edit.jpg)

it would also make sense to have a sensible starting point 1 on env temp so that it can ramp up to 110, otherwise it cant calculate the slope you want.

**Comment by diginfo** [comment]
OOps - I have to admit it's late and I have had a glass of wine :-)

**Comment by diginfo** [comment]
Absolutely my fault, thanks so much for helping.

**Comment by chron0** [comment]
:) anytime

**Comment by diginfo** [comment]
FYI - I am using it to anneal 3D printed items,

**Comment by chron0** [comment]
iirc we've implemented drag and drop on the circles in the graph so that you can move your curve along there as well

**Comment by chron0** [comment]
ah, makes sense, i was wondering what you were doing. I was thinking about using it for annealing as well.

so basically it would come down to:

Point 1 | 0 | 25
Point 2 | 900 | 110
Point 3 945 | 110
Point 4 | 1845 | 25

this would ramp up over 900 seconds to 110, hold 110 for 45 secs and then ramp down to 25 (sensible env temp) over 900 seconds again.

**Comment by chron0** [comment]
if you find a good annealing curve for a given material I'd be happy of you could share your result here or in the comment section of the apollo-ng wiki for it.
