### ISSUE TITLE
Wrong Measurement with Max31855

### ISSUE THREAD

**Issue by Meister1980** [apollo-ng/picoReflow#9]
Hello,

I have a problem with PicoReflow. The Temperature measured by PicoReflow & Max31855 is not correct. First i thought that i have a problem with the K-Type Sensor, but then I tested them at work with a Thermocouple calibrator! I tested the Sensors, my thermocouple gauge and the Max31855 (with Picoreflow).

I measured a temperature with picoreflow and it shows 100°C than i measured the same temperature with my calibrated Gauge and it shows 130°C !?

![img_20150620_102456](https://cloud.githubusercontent.com/assets/12976347/8266633/44bd768c-1739-11e5-8258-021bd8e7c781.jpg)

I tested picoReflow with the calibrator and when the calibrator says 225°C, picoreflow shows about 180°C.
 
I tested this with 3 diffent Max31855 on different boards, everytime the same Problem. I think its a Software Problem. 

Can anyone test his Pico and confirm this Problem ? I dont now what to do further ...

Greets,
Meister

**Comment by KammutierSpule** [comment]
You may would like have a look at:

http://www.eevblog.com/forum/projects/max31855-temperature-error/30/

https://translate.google.pt/translate?sl=pt&tl=en&js=y&prev=_t&hl=pt-PT&ie=UTF-8&u=http%3A%2F%2Flusorobotica.com%2Findex.php%3Ftopic%3D7908.msg88928%23msg88928&edit-text=

There are some official faulty batch being selling by major component dealers (eg: mouser, digikey..etc)

**Comment by Meister1980** [comment]
Testing with Calibrator :

Calibrator : 25°C
picoReflow: 22°C

![img_20150620_113824](https://cloud.githubusercontent.com/assets/12976347/8266822/2e4f0c76-1743-11e5-8904-6032fd5e4a48.jpg)

Calibrator : 100°C
picoReflow: 76°C

![img_20150620_113910](https://cloud.githubusercontent.com/assets/12976347/8266824/4c055a54-1743-11e5-8403-c3c3f971fb54.jpg)

Calibrator : 225°C
picoReflow: 163°C

![img_20150620_114015](https://cloud.githubusercontent.com/assets/12976347/8266827/5e8bfdae-1743-11e5-91ee-da5f2899728a.jpg)

Calibrator : 350°C
picoReflow: 252°C

![img_20150620_114111](https://cloud.githubusercontent.com/assets/12976347/8266828/729d9bf4-1743-11e5-8572-38d025b11d2c.jpg)

**Comment by KammutierSpule** [comment]
Yes it looks like it is a Max31855 faulty batch. I had the same issues while trying to make a reflow oven. In my experience the different was not so big as yours. But the behavior was the same: the more the temperature increases, the more the difference.

**Comment by Meister1980** [comment]
Dooooh ! Yes its a faulty Batch ....

2 of the Max31855 I tested where from an order last Year (Mouser). Datecode -> 1352A2 - 23AL
The third Max is from this Week from Conrad Electronic, but has the same Date Code :-(

**Comment by KammutierSpule** [comment]
The maxim IC knows it, probably Mouser/Digikey knows it too.. and still sell it that way :|

**Comment by chron0** [comment]
Meh, that's a shame and always happens when you need it the least :/ The modules we got from watterott.com have not had any issues, I've verified the metrics against a reference thermometer during dev/testing. But I had the same issue with a DS1820. As it seems to have been a HW problem, I'll close the ticket if no one raises any objections.
